version: '3.8'

services:
  api_doc:
    image: swaggerapi/swagger-editor
    environment:
      SWAGGER_FILE: /home/api-doc.yml
    ports:
      - '80:8080'
    volumes:
      - ./api-doc.yml:/home/api-doc.yml
